DISTRICT_NAMES = [
  'Aberdeen',
  'Admiralty',
  'Ap Lei Chau',
  'Causeway Bay',
  'Central',
  'Chai Wan',
  'Chek Lap Kok',
  'Cheung Chau',
  'Cheung Sha Wan',
  'Choi Hung',
  'Cyberport',
  'Deep Water Bay',
  'Diamond Hill',
  'Discovery Bay',
  'Fanling',
  'Fo Tan',
  'Heng Fa Chuen',
  'Ho Man Tin',
  'Hung Hom',
  'Jordan',
  'Knutsford Terrace',
  'Kowloon Bay',
  'Kowloon City',
  'Kowloon Tong',
  'Kwai Chung',
  'Kwai Fong',
  'Kwun Tong',
  'Lai Chi Kok',
  'Lam Tin',
  'Lamma Island',
  'Lan Kwai Fong',
  'Lantau Island',
  'Lau Fau Shan',
  'Lei Yue Mun',
  'Lo Wu',
  'Lok Fu',
  'Lok Ma Chau',
  'Ma On Shan',
  'Ma Wan',
  'Mei Foo',
  'Mid-Levels',
  'Mong Kok',
  'Ngau Tau Kok',
  'North Point',
  'Ping Chau',
  'Po Toi Island',
  'Pok Fu Lam',
  'Prince Edward',
  'Quarry Bay',
  'Repulse Bay',
  'Sai Kung',
  'Sai Wan Ho',
  'San Po Kong',
  'Sha Tin',
  'Sham Shui Po',
  'Sham Tseng',
  'Shau Kei Wan',
  'Shek Kip Mei',
  'Shek O',
  'Sheung Shui',
  'Sheung Wan',
  'Soho',
  'Stanley',
  'Tai Hang',
  'Tai Kok Tsui',
  'Tai Koo',
  'Tai O',
  'Tai Po',
  'Tai Wai',
  'Tai Wo',
  'The Peak',
  'Tin Hau',
  'Tin Shui Wai',
  'To Kwa Wan',
  'Tseung Kwan O',
  'Tsim Sha Tsui',
  'Tsing Yi',
  'Tsuen Wan',
  'Tsz Wan Shan',
  'Tuen Mun',
  'Tung Chung',
  'Wan Chai',
  'Western District',
  'Wong Chuk Hang',
  'Wong Tai Sin',
  'Yau Ma Tei',
  'Yau Tong',
  'Yuen Long'
].freeze